# El programa presupone la existencia del archivo `gsa_2022_selectedtiles.gpkg
# en `in_path` y que los productos a procesar est치n guardados en un 
# directorio `products` dentro de `in_path`.
tile: "31TBF"
in_path: "/home/franmal/1U/Tesis/metalearning/data/" # direcci칩n del directorio con los datos a procesar.
out_path: "data" # direcci칩n del directorio donde se almacenar치n los datos procesados siguiendo el formato PASTIS
patch_size: 256
grid_padding: 1
verbose: True
user: "f.maldonado@ug.uchile.cl"
password: ""

# 31TBF
# 29TNF
# 30UXU
# 32TPP
# 32UMC
# 29UNU
# 33TVN
# 31UFU
# 35TMH
# 32VNH
